### ISSUE TITLE
Github actions fail silently

### ISSUE THREAD

**Issue by leokondrashov** [vhive-serverless/invitro#248]
## Version & Branch

E2e tests on `main` branch.

## Behaviour

In recent test (https://github.com/eth-easl/loader/actions/runs/5998242750/job/16266139553#step:9:18), loader fails to run but test is considered successful.

**Comment by leokondrashov** [comment]
@cvetkovic, can you please take a look?

**Comment by cvetkovic** [comment]
Good cache. Could this solve the problem?
https://github.com/knative/serving/issues/11388#issuecomment-845787934

**Comment by leokondrashov** [comment]
> https://github.com/knative/serving/issues/11388#issuecomment-845787934

I'm not quite sure I understand what you mean by that.

Actually, I have an idea that it might happening after introduction of separate loader node.
But the issue is also that this failure is silent.

**Comment by cvetkovic** [comment]
You can try executing this command in the workflow before the step that fails. I think it's just a wrong Knative config. Probably the defaults changed during version upgrades.

**Comment by leokondrashov** [comment]
No, actually, we didn't include nodeSelector for single-node cluster. Labels should work differently in that case.
