### ISSUE TITLE
Loader stopped working after recent merge

### ISSUE THREAD

**Issue by JooyoungPark73** [vhive-serverless/invitro#293]
## Version & Branch
main
## Expected Behaviour
run example trace as in docs/loader.md
`~/loader$ go run cmd/loader.go --config cmd/config.json`
## Actual Behaviour
pod is not created, and failed to create workload in worker node
also failed to open trace memory specification file.

```
ERRO[Oct 26 00:12:49.301] Failed to open trace memory specification file.
...
DEBU[Oct 26 00:15:19.603] gRPC timeout exceeded for function trace-func-0-14278186231267686839 - rpc error: code = Unimplemented desc =
...
```

## Steps to Reproduce the Problem

1.
2.
3.

## Additional Info
@cvetkovic

**Comment by cvetkovic** [comment]
Are you sure the issue is not on the side of the Knative cluster? I am fixing the error log message, but that's not what is causing the crash.

**Comment by JooyoungPark73** [comment]
I rolled back to #291 , and working on python workload, and it works fine for now.
How is Knative cluster causing the problem?

**Comment by cvetkovic** [comment]
Ok, deploying a cluster currently and debugging.

**Comment by JooyoungPark73** [comment]
Thanks. For more info, the Loader prints out that it deployed functions in namespace default, but actually nothing is deployed.

**Comment by cvetkovic** [comment]
Solved. Please review the PR I linked to this issue.

**Comment by JooyoungPark73** [comment]
Thanks! btw, do you know why checks stopped working?

**Comment by cvetkovic** [comment]
> Thanks! btw, do you know why checks stopped working?

No idea. I don't think that's our issue. They run eventually.
