### ISSUE TITLE
HTTP mode waits for end of all invocations before writing the results

### ISSUE THREAD

**Issue by leokondrashov** [vhive-serverless/invitro#329]
## Version & Branch

main branch, HTTP mode (used by OpenWhisk and AWS Lambda modes).

## Expected Behaviour

Write `trace` logs and output files right after getting response from server.

## Actual Behaviour

Wait for all invocations and then write both to the logs and durations file.

## Steps to Reproduce the Problem

1. Run any trace with > 1 invocation in OpenWhisk or AWS Lambda mode with `trace` verbosity. Correct response info will be printed after all invocations are finished.

## Additional Info

This was originally used in OpenWhisk mode, after that extracted to InvokeHTTP function and reused by AWS Lambda mode.

**Comment by leokondrashov** [comment]
@MashaNes @cvetkovic Seems that you were the original authors of OpenWhisk mode. Is there any reason for the Wait() [here](https://github.com/vhive-serverless/invitro/blob/main/pkg/driver/http_client.go#L220)?

**Comment by cvetkovic** [comment]
This is so that OpenWhisk performance is not affected by running the workload and querying the results simultaneously.
